apiVersion: v1
kind: ReplicationController
metadata:
    name: yrc
spec:
   replicas: 3
   selector:
      env: dev    
   template:
      metadata:
        labels: 
            env: dev
      spec:
        containers:
           - name: mynginxcont
             image: nginx
             ports:
              - containerPort: 80