apiVersion: v1
kind: Pod
metadata:
  name: mypod
spec:
   containers:
    - image: mysql
      ports:
       - containerPort: 3306
      env:
       - name: MYSQL_ROOT_PASSWORD
         value: Pass@123
      name: mydbcont